# Generated by Django 5.1 on 2024-11-07 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_add_timestamps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracteristica',
            old_name='tipo',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productocaracteristica',
            name='valor',
            field=models.CharField(max_length=200),
        ),
    ]
